# Generated by Django 4.1.7 on 2023-03-16 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreD', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreR', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreE', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('salario', models.IntegerField(default=0)),
                ('bono', models.IntegerField(default=0)),
                ('numeroCel', models.IntegerField(default=0)),
                ('fechaContra', models.DateField()),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitioweb.departamento')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitioweb.rol')),
            ],
        ),
    ]
